#
# The folder structure underneath the project folder is used to create folders on disk -
# templates.yml (this file) refers to those folders. Therefore, the two files need to be
# in sync. This file contains an overview of all locations.
#


#
# The keys section contains the definitions for all the different keys.
#
keys:
  sequence:
    type:str
  project:
    type:str
  maya_extension:
        type: str
        choices:
            ma: Maya Ascii (.ma)
            mb: Maya Binary (.mb)
        default: mb
        alias: extension
  asset_type:
    type:str
  asset:
    type:str
  task:
    type:str
  shot:
    type:str
  version:
    type:sequence
  
paths:
  # Common  path definitions to use as shorthand in order to avoid repetitive and verbose
  # templates. This also makes it easy to change any of the common root paths and have the
  # changes apply to all templates that use them.
  #
  # These don't require the standard formatting (with definition and root_name) because they
  # will be set within each template that uses the alias.

  # root path
  sequence_root: /home/rapa/show/{project}/SEQ
  asset_root: /home/rapa/show/{project}/AST
  toolkit_root: /home/rapa/show/{project}/TK


  ##########################################################################################
  # Sequence pipeline


  #
  # Maya
  #
  # The location of developed maya files
  maya_sequence_root:
    definition: '@sequence_root/{sequence}/{shot}/{task}/dev/maya'
  maya_sequence_dev:
      definition: '@sequence_root/{sequence}/{shot}/{task}/dev/maya/scenes/{shot}_{task}_v{version}.{maya_extension}'
  # The location of developed maya files with tag
  maya_sequence_dev_with_tag:
      definition: '@sequence_root/{sequence}/{shot}/{task}/dev/maya/scenes/{shot}_{task}_v{version}_{tag}.{maya_extension}'
  # The location of published maya files
  maya_sequence_pub:
      definition: '@sequence_root/{sequence}/{shot}/{task}/pub/maya/scenes/{shot}_{task}_v{version}.{maya_extension}'
  # The location of published maya files with tag
  maya_sequence_pub_with_tag:
      definition: '@sequence_root/{sequence}/{shot}/{task}/pub/maya/scenes/{shot}_{task}_v{version}_{tag}.{maya_extension}'
  # The location of published maya abc files
  maya_sequence_pub_abc:
      definition: '@sequence_root/{sequence}/{shot}/{task}/dev/maya/cache/alembic/{shot}_{object}_{task}_v{version}.abc'
  
  # Rendered output
  maya_sequence_render_movie:
      definition: '@sequence_root/{sequence}/{shot}/{task}/pub/maya/scenes/{shot}_{task}_v{version}.mov'
  maya_sequence_render_exr:
      definition: '@sequence_root/{sequence}/{shot}/{task}/pub/maya/scenes/{shot}_{task}_v{version}.####.exr'
  maya_sequence_render_jpg:
      definition: '@sequence_root/{sequence}/{shot}/{task}/pub/maya/scenes/{shot}_{task}_v{version}.####.jpg'
  maya_sequence_render_png:
      definition: '@sequence_root/{sequence}/{shot}/{task}/pub/maya/scenes/{shot}_{task}_v{version}.####.png'
  
  # Capture output
  maya_sequence_capture:
      definition: '@asset_root/{asset_type}/{asset}/{task}/dev/maya/images/captures/{asset}_{task}_v{version}.jpg'

  # Playblast output
  maya_sequence_playblast:
      definition: '@sequence_root/{sequence}/{shot}/{task}/dev/maya/movies/playblast/{shot}_{task}_v{version}.%04d.jpg'

  # Ffmpeg_output
  maya_sequence_ffmpeg:
      definition: '@sequence_root/{sequence}/{shot}/{task}/pub/maya/movies/ffmpeg/{shot}_{task}_v{version}_slate.mov'

  

  #
  # Nuke
  #

  nuke_sequence_root:
      definition: '@sequence_root/{sequence}/{shot}/{task}/dev/nuke'
  nuke_sequence_dev:
      definition: '@sequence_root/{sequence}/{shot}/{task}/dev/nuke/scenes/{shot}_{task}_v{version}.nknc'
  # The location of published nuke script
  nuke_sequence_pub:
      definition: '@sequence_root/{sequence}/{shot}/{task}/pub/nuke/scenes/{shot}_{task}_v{version}.nknc'
  # The location of developed nuke script with tag
  nuke_sequence_dev_with_tag:
      definition: '@sequence_root/{sequence}/{shot}/{task}/dev/nuke/scenes/{shot}_{task}_v{version}_{tag}.nknc'
  # The location of published nuke script with tag
  nuke_sequence_pub_with_tag:
      definition: '@sequence_root/{sequence}/{shot}/{task}/pub/nuke/scenes/{shot}_{task}_v{version}_{tag}.nknc'
 
  # Rendered output
  nuke_sequence_render_movie:
      definition: '@sequence_root/{sequence}/{shot}/{task}/pub/nuke/scenes/{shot}_{task}_v{version}.mov'
  nuke_sequence_render_exr:
      definition: '@sequence_root/{sequence}/{shot}/{task}/pub/nuke/scenes/{shot}_{task}_v{version}.####.exr'
  nuke_sequence_render_jpg:
      definition: '@sequence_root/{sequence}/{shot}/{task}/pub/nuke/scenes/{shot}_{task}_v{version}.####.jpg'
  nuke_sequence_render_png:
      definition: '@sequence_root/{sequence}/{shot}/{task}/pub/nuke/scenes/{shot}_{task}_v{version}.####.png'

  # Ffmpeg_output
  nuke_sequence_ffmpeg:
      definition: '@sequence_root/{sequence}/{shot}/{task}/pub/maya/movies/ffmpeg/{shot}_{task}_v{version}_slate.mov'


  ##########################################################################################
  # Asset pipeline

  #
  # Maya
  #
  # The location of developed maya files
  maya_asset_root:
      definition: '@asset_root/{asset_type}/{asset}/{task}/dev/maya'
  maya_asset_dev:
      definition: '@asset_root/{asset_type}/{asset}/{task}/dev/maya/scenes/{asset}_{task}_v{version}.{maya_extension}'
  # The location of published maya files
  maya_asset_pub:
      definition: '@asset_root/{asset_type}/{asset}/{task}/pub/maya/scenes/{asset}_{task}_v{version}.{maya_extension}'
  # The location of developed maya files with tag
  maya_asset_dev_with_tag:
      definition: '@asset_root/{asset_type}/{asset}/{task}/dev/maya/scenes/{asset}_{task}_v{version}_{tag}.{maya_extension}'
  # The location of published maya files with tag
  maya_asset_pub_with_tag:
      definition: '@asset_root/{asset_type}/{asset}/{task}/pub/maya/scenes/{asset}_{task}_v{version}_{tag}.{maya_extension}'
  # The location of published maya abc files 
  maya_asset_pub_abc:
      definition: '@asset_root/{asset_type}/{asset}/{task}/pub/maya/scenes/{asset}_{task}_v{version}_{tag}.abc'
  
  # Rendered output
  maya_asset_render_movie:
      definition: '@asset_root/{asset_type}/{asset}/{task}/pub/maya/movies/{asset}_{task}_v{version}.mov'
  maya_asset_render_exr:
      definition: '@asset_root/{asset_type}/{asset}/{task}/pub/maya/images/exr/{asset}_{task}_v{version}.####.exr'
  maya_asset_render_jpg:
      definition: '@asset_root/{asset_type}/{asset}/{task}/pub/maya/images/jpg/{asset}_{task}_v{version}.####.jpg'
  maya_asset_render_png:
      definition: '@asset_root/{asset_type}/{asset}/{task}/pub/maya/images/png/{asset}_{task}_v{version}.####.png'
  
  # Capture output
  maya_asset_capture:
      definition: '@asset_root/{asset_type}/{asset}/{task}/dev/maya/images/captures/{asset}_{task}_v{version}.jpg'

  # Playblast output
  maya_asset_playblast:
      definition: '@asset_root/{asset_type}/{asset}/{task}/dev/maya/movies/playblast/{shot}_{task}_v{version}.%04d.jpg'
  
  # Ffmpeg_output
  maya_asset_ffmpeg:
      definition: '@asset_root/{asset_type}/{asset}/{task}/pub/maya/movies/ffmpeg/{shot}_{task}_v{version}_slate.mov